### ISSUE TITLE
Create output to virtual comport

### ISSUE THREAD

**Issue by PavelFilippovich** [mihai-dinculescu/msfs-2020-gps-link#28]
Hello! Great app! I ask you to consider the possibility of issuing data to a virtual comport. The program should create a virtual comport and send a GPS data stream to it, emulating a GPS receiver. It will be possible to check the operation of the program by connecting any GPS receiver data processing program to the virtual comport. This option is needed, for example, to use Jeppesen Flitеdesk.

**Comment by PavelFilippovich** [comment]
Perhaps the best option would be to use the NMEA-0183 RMC protocol. https://tronico.fi/OH6NT/docs/NMEA0183.pdf Page 14.

**Comment by PavelFilippovich** [comment]
Maybe this documentation will be helpful https://ge0mlib.com/papers/Protocols/SiRF_Nmea_rev3_0.pdf

**Comment by mihai-dinculescu** [comment]
Thank you for this feature request and the provided information, @PavelFilippovich.
I should find some time to look into this in the next few weeks.

The NMEA-0183 RMC protocol seems to be used by RS232 GPS Devices, which is an input supported by SkyDemon. This should make testing easy for me, as I'm already familiar with SkyDemon.

Once I get it working in SkyDemon over a virtual COM, I'll give you a shout to test it in Jeppesen Flitеdesk.

**Comment by mihai-dinculescu** [comment]
@PavelFilippovich good news, COM should be supported in version v0.3.0-alpha.1
You can grab it from https://github.com/mihai-dinculescu/msfs-2020-gps-link/releases/tag/v0.3.0-alpha.1.
There is another tool that needs to be installed, com0com. The UI has instructions on how to go about it.

I would love your feedback on the feature.

There are some decisions that I've taken that I'm not sure of:
- `PRESSURE ALTITUDE` from MSFS is reported over COM rather than the `PLANE ALTITUDE` used for X-Plane mode. `PRESSURE ALTITUDE` seems more accurate in Sky Demon when the data is sent over COM.
- A hard-coded `GPGSA` message is broadcasted every second. Its value, `$GPGSA,A,3,01,02,03,04,05,06,07,08,09,10,11,12,1.0,1.0,1.0*30\r\n`, should mean perfect accuracy.
- A pair of `GPGGA` and `GPRMC` messages are broadcasted each interval. `GPGGA` contains the location and altitude. `GPRMC` contains the location, ground speed and track.
- The NMEA protocol contains some fields for which SimConnect doesn't provide a value.
- `PDOP` - I default it to `1.0`
- `HDOP` - I default it to `1.0`
- `VDOP` - I default it to `1.0`
- `Geoid Separation` - I default it to `0.0`
- `Age of Diff. Corr. ` - I left it empty
- `Diff. Ref. Station ID` - I left it empty
- `Magnetic Variation` - I left it empty because I calculated Course Over Ground as `GPS GROUND MAGNETIC TRACK` - `MAGVAR`. Not sure how correct this is.

**Comment by PavelFilippovich** [comment]
Great news!
Connection to Jeppesen Flitеdesk successful!
3D GPS coordinates work!

- The current coordinates are correct.
- Height is correct.
- Time is right.
- Heading with an error of 5 degrees. MSFS 2020 shows 145 degrees, Jeppesen sees 150. Checked in Spain.

More note. The choice of com port speed should be made from the standard values 4800, 9600, 19200, 38400, 57600, 115200.

There are tricks in connection. I will test further. I'll let you know the result.

**Comment by PavelFilippovich** [comment]
![2022-11-06_19-19-28](https://user-images.githubusercontent.com/116830995/200182126-523c4df2-81d2-42a6-bd6d-19e5ab814ca7.png)

Jeppesen Flitеdesk setup.

**Comment by PavelFilippovich** [comment]
It would also be great to store the settings of the last run.

**Comment by PavelFilippovich** [comment]
There are no problems with connection. Everything is working. I tested the comport at speeds of 9600 and 38400.

**Comment by mihai-dinculescu** [comment]
Thank you very much for the prompt testing and feedback, @PavelFilippovich .
There's a new alpha release out: https://github.com/mihai-dinculescu/msfs-2020-gps-link/releases/tag/v0.3.0-alpha.2.

I think that I've managed to fix the heading error.
I've also changed the Baud rate to be a dropdown with fixed options.

I have created a separate issue for the persistence of settings: #30.

There is still one bug I want to fix before the general release. The broadcaster currently hangs when sending messages over COM when no navigation app is connected.

**Comment by PavelFilippovich** [comment]
Thank you so much for making the changes!

Unfortunately, the course has not changed. Photos in the application. One from MSFS2020 the other from Jeppesen Flitedesk. The place of fixing the course is also attached.

![2022-11-07_21-14-31](https://user-images.githubusercontent.com/116830995/200385893-77ab8b31-532a-4e39-8cb7-6c4d788a6ba6.png)

![2022-11-07_21-14-52](https://user-images.githubusercontent.com/116830995/200385907-ba8ef93a-be39-4083-bae8-e5d44332a00b.png)

![2022-11-07_21-15-27](https://user-images.githubusercontent.com/116830995/200385918-3aeed46f-8e87-472a-a270-68d61cef37f6.png)

The comport speed of 14400 is not needed. Better add 115200.

Everything else works, as before, excellent!

Update: I checked the information on the Jeppesen Flitedeсk documentation. I was wrong. Jeppesen does not show the exact course. Do not look for a bug in your program.

**Comment by mihai-dinculescu** [comment]
Thank you very much for the quick feedback @PavelFilippovich.

I have tweaked the baud rate speeds and have addressed an edge case in the COM setup documentation.
Version v0.3.0 contains these changes. https://github.com/mihai-dinculescu/msfs-2020-gps-link/releases/tag/v0.3.0

I will close this issue now.

Thanks again for all the support and feedback. It's been most useful.
Please don't hesitate to open other issues if you encounter problems or if you have other requests.

**Comment by PavelFilippovich** [comment]
Tested at a speed of 115200. Everything works well! Thank you!
